from enum import Enum

class AlertType(Enum):
    LOSS_THRESHOLD_REACHED = "LOSS_THRESHOLD_REACHED"
    WIN_THRESHOLD_REACHED = "WIN_THRESHOLD_REACHED"
    USER_INACTIVE = "USER_INACTIVE"
    AUTOPLAY_STOPPED = "AUTOPLAY_STOPPED"
