from enum import Enum

class BettingStrategyType(Enum):
    FIXED = "FIXED"
    PERCENTAGE = "PERCENTAGE"
    MARTINGALE = "MARTINGALE"
    REVERSE_MARTINGALE = "REVERSE_MARTINGALE"
    FIBONACCI = "FIBONACCI"
    D_ALEMBERT = "D_ALEMBERT"